[package]
name = "via-router"
version = "1.0.1"
authors = ["Zachary Golba <zachary.golba@postlight.com>"]
edition = "2021"
license = "MIT"
description = "A fast and flexible http router."
homepage = "https://github.com/zacharygolba/via"
repository = "https://github.com/zacharygolba/via"
