[package]
name = "via-serve-static"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
mime_guess = "2.0.4"

[dependencies.tokio]
version = "1.38.0"

[dependencies.via]
features = ["file-system"]
path = "../.."
