[package]
name = "tls-rustls"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls-pemfile = "2.1"
tokio-rustls = "0.26"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
via = { path = "../..", features = ["http2", "rustls"] }
