[package]
name = "tls-native"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
native-tls = "0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
via = { path = "../..", features = ["http2", "native-tls"] }
