#
# Copied verbatim from Tide and then slightly modified. Great work everyone!
#
# https://github.com/http-rs/tide/blob/main/.github/workflows/ci.yaml
#
name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: test router
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package via-router --features lru-cache

  fmt_clippy_and_docs:
    name: fmt, clippy, and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: setup
        run: |
          rustup component add clippy rustfmt
          rustc --version

      - name: clippy
        run: cargo clippy --tests --examples -- -D warnings

      - name: fmt
        run: cargo fmt --all -- --check

      - name: docs
        run: cargo doc --no-deps
